config/routes.rb
AuthApp::Application.routes.draw do

  root :to => "home#index"  
  # get "home/index"
  get 'search', to: 'home#search'
  
  resources :inventories
  resources :inventory_templates
  resources :reservations
  resources :restaurants
  resources :rewards
   
  devise_for :owners
  devise_for :users, controllers: { 
    omniauth_callbacks: "omniauth_callbacks" 
  }
   
end

app/models/inventory_template.rb
class InventoryTemplate < ActiveRecord::Base
  attr_accessible :start_time, :end_time, :name, :primary, 
                  :quantity_available, :restaurant_id
  
  validates :restaurant_id, :presence => true
  validates :name,          :presence => true
  validates :start_time,    :presence => true
  validates :end_time,      :presence => true
  validates :quantity_available, :presence => true,
            :numericality => { :greater_than_or_equal_to => 1 }

  belongs_to :restaurant
end

app/controllers/inventory_templates_controller.rb
class InventoryTemplatesController < ApplicationController
  before_filter :authenticate_owner!, 
                except: [:index, :show]
   
  # GET /inventory_templates
  # GET /inventory_templates.json
  def index
    @inventory_templates = InventoryTemplate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventory_templates }
    end
  end
  
  # GET /inventory_templates/1
  # GET /inventory_templates/1.json
  def show
    @inventory_template = InventoryTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory_template }
    end
  end

  # GET /inventory_templates/new
  # GET /inventory_templates/new.json
  def new
    @inventory_template = InventoryTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory_template }
    end
  end

  # GET /inventory_templates/1/edit
  def edit
    @inventory_template = InventoryTemplate.find(params[:id])
  end

  # POST /inventory_templates
  # POST /inventory_templates.json
  def create
    @inventory_template = InventoryTemplate.new(params[:inventory_template])

    respond_to do |format|
      if @inventory_template.save
        format.html { redirect_to @inventory_template, notice: 'Inventory template was successfully created.' }
        format.json { render json: @inventory_template, status: :created, location: @inventory_template }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventory_templates/1
  # PUT /inventory_templates/1.json
  def update
    @inventory_template = InventoryTemplate.find(params[:id])

    respond_to do |format|
      if @inventory_template.update_attributes(params[:inventory_template])
        format.html { redirect_to @inventory_template, notice: 'Inventory template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_templates/1
  # DELETE /inventory_templates/1.json
  def destroy
    @inventory_template = InventoryTemplate.find(params[:id])
    @inventory_template.destroy

    respond_to do |format|
      format.html { redirect_to inventory_templates_url }
      format.json { head :no_content }
    end
  end 

end

app/helpers/inventory_templates_helper.rb
module InventoryTemplatesHelper
end

app/views/inventory_templates/_form.html.erb
<%= simple_form_for([@inventory_template], html: { class: "form-horizontal"}) do |f| %>

  <%= f.association :restaurant, label: "Restaurant" %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :quantity_available, label: "Quantity Available" %>
  <%= f.input :start_time, :minute_step => 15, label: "Start Time" %>
  <%= f.input :end_time, :minute_step => 15, label: "End Time" %>
  <%= f.input :primary, label: "Primary" %>
 
  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/inventory_templates/edit.html.erb
<h1>Editing inventory_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_template %> |
<%= link_to 'Back', inventory_templates_path %>

app/views/inventory_templates/index.html.erb
<h1>Listing inventory templates</h1>

<table>
  <tr>
    <th>Restaurant</th>
    <th>Name</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Quantity available</th>
    <th>Primary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventory_templates.each do |inventory_template| %>
  <tr>
    <td><%= inventory_template.restaurant.name %></td>
    <td><%= inventory_template.name %></td>
    <td><%= mtime(inventory_template.start_time) %></td>
    <td><%= mtime(inventory_template.end_time) %></td>
    <td><%= inventory_template.quantity_available %></td>
    <td><%= inventory_template.primary %></td>
    <td><%= link_to 'Show', inventory_template %></td>
    <td><%= link_to 'Edit', edit_inventory_template_path(inventory_template) %></td>
    <td><%= link_to 'Destroy', inventory_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inventory template', new_inventory_template_path %>

app/views/inventory_templates/new.html.erb
<h1>New inventory_template</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_templates_path %>

app/views/inventory_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Restaurant:</b>
  <%= @inventory_template.restaurant.name %>
</p>

<p>
  <b>Name:</b>
  <%= @inventory_template.name %>
</p>

<p>
  <b>Start time:</b>
  <%= mtime(@inventory_template.start_time) %>
</p>

<p>
  <b>End time:</b>
  <%= mtime(@inventory_template.end_time) %>
</p>

<p>
  <b>Quantity available:</b>
  <%= @inventory_template.quantity_available %>
</p>

<p>
  <b>Primary:</b>
  <%= @inventory_template.primary %>
</p>


<%= link_to 'Edit', edit_inventory_template_path(@inventory_template) %> |
<%= link_to 'Back', inventory_templates_path %>