config/routes.rb
AuthApp::Application.routes.draw do

  root :to => "home#index"  
  # get "home/index"
  get 'search', to: 'home#search'
  
  resources :inventories
  resources :inventory_templates
  resources :reservations
  resources :restaurants
  resources :rewards
   
  devise_for :owners
  devise_for :users, controllers: { 
    omniauth_callbacks: "omniauth_callbacks" 
  }
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # root route
  def index
    if user_signed_in?
      @rewards = current_user.rewards
    end
  end

 # GET /search/:search_term
  #todo: refactor
  def search
    @search = Hash.new
    @search["cuisine"]  = "Any" unless params[:cuisine].present?
    @search["price"]    = "Any" unless params[:price].present?
    @search["location"] = "Any" unless params[:location].present?
    @search["cuisine"]  ||= params[:cuisine]
    @search["price"]    ||= params[:price]
    @search["location"] ||= params[:location]

    if @search["price"][0]!="Any" and 
          @search["cuisine"][0]!="Any" 
      # @restaurants = Restaurant.near(@search, 10).limit(10)
      @search_results = Restaurant.with_cuisine(@search["cuisine"]).with_price(@search["price"])
    elsif @search["cuisine"][0]=="Any" and 
            @search["price"][0]!="Any" 
      @search_results = Restaurant.with_price(@search["price"])
    elsif @search["cuisine"][0]!="Any" and 
            @search["price"][0]=="Any" 
      @search_results = Restaurant.with_cuisine(@search["cuisine"])
    else 
      @search_results = Restaurant.all
    end
  end

end   

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to Restaurant Booking System</h1>
<p>Simple Restaurant Booking System on RoR </p>

<%= form_tag("/search", method: "get") do %>
  <label for="price">Price</label>
  <%= select_tag "price" , "<option selected=\"selected\">Any</option><option>1</option><option>2</option><option>3</option><option>4</option>".html_safe, :multiple => true, :include_blank => false%>  
  <label for="cuisine">Cuisine</label>
  <%= select_tag "cuisine" , "<option selected=\"selected\">Any</option><option>Thai Food</option><option>Chinese Food</option><option>Indian Food</option>".html_safe, :multiple => true, :include_blank => false%>
  <label for="location">Location</label>
  <%= text_field_tag(:location) %>
  <%= submit_tag("Search") %>
<% end %>
<p />

<% if user_signed_in? or owner_signed_in? %>
  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <p />
  
    <% unless @rewards.empty? %>
      <table>
        <tr>
          <th>Restaurant</th>
          <th>Points_total</th>
          <th>Points_pending</th>
          <th>Description</th>
        </tr>

      <% if @rewards %>
      <% @rewards.each do |reward| %>
        <tr>
          <td><%= reward.reservation.restaurant.name %></td>
          <td><%= reward.points_total %></td>
          <td><%= reward.points_pending %></td>
          <td><%= reward.description %></td>
        </tr>
      <% end %>
      <% end %>
      </table>
    <% end %>



  <%else%>  
    <%= link_to "Logout", destroy_owner_session_path, method: :delete %>
  <% end %>     
<% else %>
  <%= link_to "Login as user", new_user_session_path %><br />
  <%= link_to "Registration for users", new_user_registration_path %><p />

  <%= link_to "Login as Owner", new_owner_session_path %><br />
  <%= link_to "Registration for Owners", new_owner_registration_path %>
<% end %>   

<p />
 <b>Section below editable only by Users</b><br />
 User sees the reservations he made<br />
 Owner sees the reservations that belong to him restaurants<br />
 <%= link_to "Reservations", reservations_path %><p />

 <b>Sections below editable only by Restaurant Owners</b><br />
 <%= link_to "Restaurants", restaurants_path %><br />
 <%= link_to "Inventories", inventories_path %><br />
 <%= link_to "Inventory Templates", inventory_templates_path %><br />

app/views/home/search.html.erb
<h1>Search Results</h1>
<p>You seached for 
  <% @search.each do|k,v| %>
    <%= v %> 
    <%= k %>
  <% end %>
 </p>

<% if @search_results %>
  <table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th>Budget</th>
    <th>Cuisine</th>
    <th>Misc</th>
    <th>Lat</th>
    <th>Lng</th>
    <th></th>
  </tr> 

  <% @search_results.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.category %></td>
      <td><%= restaurant.price %></td>
      <td><%= restaurant.budget %></td>
      <td><%= restaurant.cuisine %></td>
      <td><%= restaurant.misc %></td>
      <td><%= restaurant.lat %></td>
      <td><%= restaurant.lng %></td>
      <td><%= link_to 'Show', restaurant %></td>
    </tr>
  <% end %>
</table>  

<br />
<% end %>