config/routes.rb
AuthApp::Application.routes.draw do

  root :to => "home#index"  
  # get "home/index"
  get 'search', to: 'home#search'
  
  resources :inventories
  resources :inventory_templates
  resources :reservations
  resources :restaurants
  resources :rewards
   
  devise_for :owners
  devise_for :users, controllers: { 
    omniauth_callbacks: "omniauth_callbacks" 
  }
   
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :category, :lat, :lng, :misc, 
                  :name, :owner_id, :price, :budget, :cuisine

  validates :name, :presence => true
  validates :lng,   :presence => true
  validates :lat,   :presence => true
  validates :price,   :presence => true
  validates :budget,   :presence => true
  validates :cuisine,   :presence => true
  validates :price, :numericality => { 
                :greater_than_or_equal_to => 1, 
                :less_than_or_equal_to => 5  }

  has_many :reservations
  has_many :inventories
  has_many :inventory_templates

  belongs_to :owner

  # scope :with_cuisine, -> (cuisine) do 
  #   where('cuisine LIKE ?', "%#{cuisine}%" ) unless cuisine.present?
  # end

  #todo: refactor
  class << self
    def with_price price
      if price.class == Array
        case price.length
          when 2..5
            where("price >= ? AND price <= ?", price[0].to_i, price.last.to_i)
          else
            where(price: price[0])
        end
      else
        where(price: price)
      end
    end

    def with_cuisine cuisine
      if cuisine.class == Array
        case cuisine.length
          when 2
            where('cuisine LIKE ? or cuisine LIKE ?', "%#{cuisine[0]}%", "%#{cuisine[1]}%")
          when 3
            where('cuisine LIKE ? or cuisine LIKE ? or cuisine LIKE ?', "%#{cuisine[0]}%", "%#{cuisine[1]}%", "%#{cuisine[2]}%")
          else
            where('cuisine LIKE ?', "%#{cuisine[0]}%")
        end
      else
        where('cuisine LIKE ?', "%#{cuisine}%")
      end
    end

    def with_location location
      where('location LIKE ?', "%#{location}%")
    end
  end


end

   

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :authenticate_owner!, 
                except: [:index, :show]
  
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
#    @restaurants = current_owner.restaurants

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @image_tag_string = "http://maps.google.com/maps/api/staticmap?key=AIzaSyC77WBfl-zki0vS7h9zyKyYg3htKcERvuo&size=550x300"
    @image_tag_string << "&center=#{@restaurant.lat}%2C#{@restaurant.lng}"
    # @image_tag_string << "&markers=icon:http://tinyurl.com/o39bbb3%7C#{@restaurant.lat}%2C#{@restaurant.lng}"
    # @image_tag_string << "&markers=icon:http://tinyurl.com/oyoepzu%7C#{@restaurant.lat}%2C#{@restaurant.lng}"
    @image_tag_string << "&markers=icon:http://tinyurl.com/pgdsbxb%7C#{@restaurant.lat}%2C#{@restaurant.lng}"
    @image_tag_string << '&sensor=false&zoom=15'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end
     
  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.owner_id = current_owner.id

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.owner_id = current_owner.id

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= simple_form_for([@restaurant], html: { class: "form-horizontal"}) do |f| %>

  
  <%= f.input :name, label: "Name" %>
  <%= f.input :category, label: "Type/Category" %>
  <%= f.input :cuisine, label: "Cuisine" %>
  <%= f.input :price, label: "Price" %>
  <%= f.input :budget, label: "Budget" %>
  <%= f.input :lat, label: "Latitude" %>
  <%= f.input :lng, label: "Longitude" %>
  <%= f.input :misc, label: "Misc", as: :text, input_html: { rows: "3"} %>
 
  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
   
<% end %> 

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <tr>
<!--    <th>Owner</th>-->
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th>Budget</th>
    <th>Cuisine</th>
    <th>Misc</th>
    <th>Lat</th>
    <th>Lng</th>
    <th></th>
<!--    <th></th>
    <th></th>-->
  </tr> 

<% @restaurants.each do |restaurant| %>
  <tr>
<!--    <td><%= restaurant.owner.owner_name %></td>-->
    <td><%= restaurant.name %></td>
    <td><%= restaurant.category %></td>
    <td><%= restaurant.price %></td>
    <td><%= restaurant.budget %></td>
    <td><%= restaurant.cuisine %></td>
    <td><%= restaurant.misc %></td>
    <td><%= restaurant.lat %></td>
    <td><%= restaurant.lng %></td>
    <td><%= link_to 'Show', restaurant %></td>
<!--    <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>-->
<!--    <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>
 

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
 
<table>
<tr>
  <td>
     <%= image_tag @image_tag_string %><br/>
  </td>
  <td align="left">
    <p>
      <b>Owner:</b>
      <%= @restaurant.owner.owner_name %>
    </p>

    <p>
      <b>Name:</b>
      <%= @restaurant.name %>
    </p>

    <p>
      <b>Category:</b>
      <%= @restaurant.category %>
    </p>

    <p>
      <b>Cuisine:</b>
      <%= @restaurant.cuisine %>
    </p> 

    <p>
      <b>Price:</b>
      <%= @restaurant.price %>
    </p>

    <p>
      <b>Budget:</b>
      <%= @restaurant.budget %>
    </p>

    <p>
      <b>Misc:</b>
      <%= @restaurant.misc %>
    </p>

    <p>
      <b>Lat:</b>
      <%= @restaurant.lat %>
    </p>

    <p>
      <b>Lng:</b>
      <%= @restaurant.lng %>
    </p>
  </td>
</tr>
</table>

Available Bookings<br>
<% @restaurant.inventories.each do |n| %>
<%= n.date %> <%= n.start_time.hour %>:<%= n.start_time.min %> <%= n.quantity_available %> 

<% if current_user.nil? then %>
<%= link_to "Login", new_user_session_path %> to Book
<% else%>
  <%= link_to 'Book Now', new_reservation_path(:restaurant_id=>@restaurant.id,:day=>n.date.day,:month=>n.date.month,:year=>n.date.year) %>
<% end %>
<br>
<% end %>

<%= current_user.nil? ? 'yes' : 'no' %>

<br>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>